export const GET_PRODUCTS = 'GET_PRODUCTS';
export const DELETE_CATEGORY = 'DELETE_CATEGORY'; // Habria que sacar el axios delete y en el reducers hacer un filter...
export const SET_CATEGORY = 'SET_CATEGORY';
export const DELETE_PROD_CATEGORY = 'DELETE_PROD_CATEGORY';
export const PUT_CATEGORY = 'PUT_CATEGORY';
export const POST_CATEGORY = 'POST_CATEGORY';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CARRITO = 'GET_CARRITO';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const PUT_PRODUCT = 'PUT_PRODUCT';
export const DELETE_PRODUCT = ' DELETE_PRODUCT';
export const DELETE_PROD_CART = 'DELETE_PROD_CART';
export const SET_CANTIDAD = 'SET_CANTIDAD';
export const ADD_TO_CART = 'ADD_TO_CART';
