export const GET_PRODUCTS = 'GET_PRODUCTS';
export const POST_CATEGORY = "POST_CATEGORY";
export const PUT_CATEGORY = "PUT_CATEGORY";
export const POST_PRODUCTS = 'POST_PRODUCTS';
export const PUT_PRODUCTS = 'PUT_PRODUCTS';

